services:
  db:
    image: postgres:16.6
    container_name: library_postgres
    shm_size: 128mb
    restart: always
    ports:
      - "7000:5432"  # host:container
    environment:
      POSTGRES_DB: LibraryDb
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myVerySecurePassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend/LibraryAPI
      dockerfile: LibraryAPI/Dockerfile
    image: online-library-backend:latest
    container_name: library_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=LibraryDb;Username=myUser;Password=myVerySecurePassword;
    depends_on:
      - db
    ports:
      - "5000:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend/my-react-app
      dockerfile: Dockerfile
    image: online-library-frontend:latest
    container_name: library_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  postgres_data:
